source "https://rubygems.org"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "sprockets-rails"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# Authentication and authorization
gem "devise"
gem "pundit"

# Background jobs
gem "sidekiq"
gem "redis", ">= 4.0.1"

# File uploads via ActiveStorage to S3
gem "aws-sdk-s3", require: false
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
